import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Grid, Container } from "@mui/material";
import ContainerTitle from "@/components/containerTitle";

export default function Home() {
  return (
    <>
      <Head>
        <title>beije | Kendi paketini oluştur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Grid container>
            <Grid item xs={12} sm={6}>
              <ContainerTitle />
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  );
}
