import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Grid, Container } from "@mui/material";
import ContainerTitle from "@/components/containerTitle";
import ContainerContent from "@/components/containerContent";
import ContainerRight from "@/components/containerRight";

export default function Home() {
  return (
    <>
      <Head>
        <title>beije | Kendi paketini oluştur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <body className={styles.main}>
        <Container>
          <Grid container marginTop="8rem">
            <Grid item xs={12} md={6}>
              <ContainerTitle />
              <ContainerContent />
            </Grid>
            <Grid item xs={12} md={1}></Grid>
            <Grid item sx={{ display: { xs: "none", md: "block" } }} md={5}>
              <ContainerRight />
            </Grid>
          </Grid>
        </Container>
      </body>
    </>
  );
}
